#!/bin/bash

docker run -it --rm \
    -v "${PWD}/test/autobahn/fuzzingclient.json:/fuzzingclient.json" \
    -v "${PWD}/_build/reports:/reports" \
    --name nomad \
    --network="host" \
    crossbario/autobahn-testsuite \
    wstest --mode fuzzingclient \
      -w ws://0.0.0.0:2112
